# Generated by Django 5.1 on 2024-09-03 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ingresos',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
