# Generated by Django 5.1 on 2024-09-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_alter_gastos_descripcion_alter_ingresos_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='monto',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ingresos',
            name='monto',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
