# Generated by Django 5.1 on 2024-09-03 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_alter_gastos_monto_alter_ingresos_monto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flujodecaja',
            options={'verbose_name': 'Flujo de Caja', 'verbose_name_plural': 'Flujos de Caja'},
        ),
        migrations.AlterModelOptions(
            name='gastos',
            options={'verbose_name': 'Gasto', 'verbose_name_plural': 'Gastos'},
        ),
        migrations.AlterModelOptions(
            name='ingresos',
            options={'verbose_name': 'Ingreso', 'verbose_name_plural': 'Ingresos'},
        ),
    ]
