# Generated by Django 5.1 on 2024-09-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0004_alter_flujodecaja_options_alter_gastos_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flujodecaja',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flujodecaja',
            name='total_gastos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flujodecaja',
            name='total_ingresos',
            field=models.IntegerField(default=0),
        ),
    ]
