# Generated by Django 5.1 on 2024-09-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0005_flujodecaja_balance_flujodecaja_total_gastos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresos',
            name='monto',
            field=models.FloatField(),
        ),
    ]
