# Generated by Django 5.1 on 2024-09-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0006_alter_ingresos_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresos',
            name='monto',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
