# Generated by Django 5.1 on 2024-09-09 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0007_alter_ingresos_monto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flujodecaja',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='flujodecaja',
            name='total_gastos',
        ),
        migrations.RemoveField(
            model_name='flujodecaja',
            name='total_ingresos',
        ),
    ]
