# Generated by Django 5.1 on 2024-09-21 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0008_remove_flujodecaja_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
