# Generated by Django 5.1 on 2024-09-21 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0009_alter_gastos_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
